### ISSUE TITLE
should webpack be a peerDependency?

### ISSUE THREAD

**Issue by vvo** [nealgranger/metalsmith-webpack#6]
I feel like the user should be able to chose his own webpack version. It would also mean you, as a maintainer do not have to deal with webpack upgrades.

What do you think?

**Comment by vvo** [comment]
cc @nealgranger

**Comment by 10xjs** [comment]
@vvo That is a good idea. I'll changes this in`2.0` with confirmed support for webpack 2.

**Comment by vvo** [comment]
Yeah! Thanks :)

**Comment by 10xjs** [comment]
@vvo I'm publishing a `v2.0.0-alpha.1` now for ya.

**Comment by vvo** [comment]
Nice thanks

**Comment by 10xjs** [comment]
@vvo `npm i ms-webpack@next`
